# -*- coding: utf-8 -*-
"""newpython.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rLI5xBRxVCZ5hegFcAv9sLQBIi12l1a0
"""

# BEGINNERS PYTHON



print("hello world!");

print("0----");
print(" ||||");

print("*" * 10);

price=10;
print("price");

print(price);

price =10;
name ="mosh";
rating=9.8;
is_boolean = False ;
print(is_boolean);

name='john smith';
age=20;
pateint="new";
name = input("What is your name ? ");
print("Hi " + name);

name = input("what is your name ? ");
color = input("your fav color ");
print( name + " likes " + color
);

dob = input("Birth year :-");
# age = (2023 - dob);
# 2023 - "2003" This is what it thinks because in pyhon the input is always considered as string
age = 2023 - int(dob);
print(age);

print(type(age));

weight = input("enter the wieght in pounds ");
kg = float(weight) / 2.2046 ;
print(kg);

print ('''hello
this is next line
new email ;
 ''')

name = "iramane";
print(name[0]);
print(name[-1]);

print(name[0:3]);

print(name[1:]);

name = "jeneefeer"
print(name[1:-1]);

# Formatted Strings in python
first = 'ira';
last = 'mane';
message = first + "[" + last + "] is a coder " ;
# print(message);
msg = f'{first} [{last}] is a coder';
print(msg);

# string methods
course = "pyhton for starter";
print(len(course));
print(course.upper());
print(course);

print(course.find('f'));

print(course.replace('for','to start for'));

print("python" in course);

print(course.title());

# arithmetic operations
print(10 / 3);
print(10 // 3);
print(10 % 3);
print( 10 ** 3);
x =12;
x+=3;
print(x);

# operator precedence
# parenthesis
# exponentiation  2 ** 3
# multiplication and division
# addition and subtraction

# math function
x = 2.9;
print(round(x));
print(abs(-9));

import math
# Module of python
print(math.ceil(2.9));

# control statements
is_hot = False;
is_cold = True;
if is_hot:
  print("its a hot day")
if is_cold:
    print("is cold day")
else:
   print("is a lovely day")

goodcredit = True;
if (goodcredit):
  print("down payment is 10%");
else:
  print("down payment is 20%");

# LOgical operations
is_highincome = False;
is_goodcredit = True;
# if is_highincome and is_goodcredit :
#   print("elgible for loan");
if is_highincome or is_goodcredit :
  print("elgible for loan");

temp = 30;
if temp>30:
  print("it is a hot day ");
else:
  print("it is a cold day");

name = input("Type your name ");
if len(name)<3:
  print("too short");
if len(name)>50:
  print("too long");
elif len(name)>3:
  print("name is good to go")

# Weight Converter
wgt = input("Weight ?");
value = input("(L)bs or (K)g ?")
if value.upper()=="L":
  wgt=int(wgt)*0.45;
  print (f'your weight is {wgt}');
elif value.upper()=="K":
  wgt = int(wgt) //0.45;
  print (f'your weight is {wgt}');

# while loops
i =1;
while i<5:
  print(i)
  i = i+1;
  print("Done")

# guess game
num = 9;
i=0;
while i<3:
   val = int(input("Guess ? "))
   i = i+1;
   if val==num:
    print("You won");
    break
else:
  print("You lost")

# car game
inp = input(">")
if inp.upper()=="help":
  print ("start for starting the car , stop to stop the car ,quit to stop")

# for loops
for item in 'python':
  print(item);

# Print first 10 natural numbers using while loop
i = 1;
while i<10:
  print(i)
  i+=1

name = input("What is your name ?")
print(name)

print("Hello World")

a = 5
b = 6
print(type(a))
print("a+b = ",a+b)

a = 100
if (a%2==0):
  print("Even Numbers")
else:
  print("Odd number")

num1 = 4
num2 = 5
print(type(num1))
sum = num1+num2

print(sum)

"""When we assign value to variable it is taken as the data type of that value but taking input it always takes in string"""

# TO FIND IF ANY SUBSTRING IS PRESENY IN THE STRING
name="Ira Mane"
print('I' in name)

# Logical operator
# or and not

# Is person elgible to vote or not
age  = int(input("What is your age ? "))
if age>=18:
  print("You can Vote")
else:
  print("You cannot vote")

# Write a program to diaply hello if user has enter the number multiple of 5
num = int(input("Enter a number"))
if num%5==0:
  print("Hello !")
else:
  print("Not a multiple of 5")

# Write a program to get the last digit of number
num = int(input("Enter a number"))
print(num%10)

# Write a program to check number is three digit or not
num = input("Enter a number ")
if len(num)!=3:
  print("Not three digit")
else:
  print("Three digit")

# To find the letter netr is vowel or not
vow = "aeiou"
ch = input("Enter a letter ")
if ch.lower() in vow:
  print("Vowel")
else:
  print("No vowel")

# Write a program for simple calculator
num1 = int(input("Enter number one "))
num2 = int(input("Enter number two "))
op = input("Enter operator ")
if op == "+":
  print(num1 + num2)
elif op == "-":
  print(num1-num2)
elif op == "*":
  print(num1*num2)
elif op == "/":
  print(num1 / num2)
else:
  print("Invalid operator ")

# range
print(range(5))

# While loops
# star pattern
i = 1
while i<=5:
  print(i * "*")
  i = i+1

inti = 10
sum1 = 0
while (inti <0):
  sum1 = sum1+inti
  inti = inti -1
print(sum)

# List
marks = [100,98,87,'maths']
# print(marks)
# print(marks[1])
# print(marks[3])
# print(marks[-1])
# print(marks[0:2])
# marks.append(99)
# print(marks)
# marks.insert(0,88)
# print(marks)
print(100 in marks)
print(len(marks))
marks.clear()
print(marks)

students = ["ira" , "isha" , "megha" , "ruby" , "tony" , " mony"]

for item in students:
  if item == "ruby":
    break
  print(item)

students = ["ira" , "isha" , "megha" , "ruby" , "tony" , " mony"]

for item in students:
  if item == "ruby":
    continue
  print(item)

# Tuple cannot be modified
marks = (98,95,97,97,97)
print(marks.count(97))
print(marks.index(97))

# Set  doen not contain duplication , index doenot index
marks = {56,67,54,21}

# Dictionary
marks = {"eng":99 , "maths" : 98 ,"science" : 98}
print(marks["eng"])
marks["bio"] = 99
print(marks)

# Functions
# in build
# modul
# user defined

# import math
# print(dir(math))
from math import sqrt
print(sqrt(16))

# User defined
#  syntax
# def functionname (parameter):
#   do something

def sum_num(first , second):
  print(first+second)

sum_num(1,2)

x = 5
print(complex(x))

txt = "ehlloe"
print(txt[0:3])

age = 36
txt = "My name is John, and I am {}"
print(txt.format(age))

fruits = {"apple", "banana", "cherry"}
more_fruits = ["orange", "mango", "grapes"]
fruits.update(more_fruits)
print(fruits)

import numpy as np
list1 = ["hello" , "hi" , "hiee"]
array1 = np.array(list1)
print(array1)
type(array1)

